# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Windows Shell
nav:
- Home: index.md
- Introduction: introduction/introduction.md
- Select and Install Shell Software: install/install.md
- User Environment Basics: user-env/user-env.md
- Batch File Basics: batch-file-basics/batch-file-basics.md
- Batch File Best Practices: best-practices/best-practices.md
- Useful Command Examples: useful-commands/useful-commands.md
- Useful Batch File Examples: useful-batch-files/useful-batch-files.md
- Useful Windows Examples: useful-windows/useful-windows.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Resources: resources/resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Extra options
# Use extra CSS to customize styles, based on theme
extra_css:
- 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't include the URL because don't really want direct editing on content and editor icons are irritating
# repo_url:  https://github.com/OpenWaterFoundation/owf-learn-linux-shell
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation Learn Windows Shell
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  favicon: 'images/OWF-Logo-Favicon-32x32.ico'
  name: material
